name: Build App

on:
  push:
    branches: ["main"]

jobs:
  build-app:
    name: build-app
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run build
      - run: git add -f dist
      - run: git commit -m "auto generating build files"
      - run: git fetch origin main
      - run: git push origin HEAD:main
